# Generated by Django 6.0.4 on 2026-05-05 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("timesheets", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.TextField()),
                ("file_type", models.TextField(blank=True, null=True)),
                ("file_path", models.TextField(blank=True, null=True)),
                ("client_name", models.TextField(blank=True, null=True)),
                ("month_year", models.TextField(blank=True, null=True)),
                ("records_parsed", models.IntegerField(default=0)),
                ("status", models.TextField(default="uploaded")),
                ("error_message", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "file_upload_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PmoTimesheetData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.TextField()),
                ("employee_code", models.TextField()),
                ("employee_name", models.TextField()),
                ("primary_skill", models.TextField(blank=True, null=True)),
                ("po_number", models.TextField(blank=True, null=True)),
                ("start_date", models.TextField(blank=True, null=True)),
                ("end_date", models.TextField(blank=True, null=True)),
                ("timesheet_month", models.TextField()),
                ("timesheet_year", models.TextField(blank=True, null=True)),
                ("billing_rate", models.FloatField(blank=True, null=True)),
                ("leaves_taken", models.IntegerField(default=0)),
                ("dates_of_leaves", models.TextField(blank=True, null=True)),
                ("compoff_days", models.IntegerField(default=0)),
                ("compoff_dates", models.TextField(blank=True, null=True)),
                ("total_leave", models.IntegerField(default=0)),
                ("pmo_billed_amount", models.FloatField(blank=True, null=True)),
                ("source_file", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.TextField(default="pending")),
            ],
            options={
                "db_table": "pmo_timesheet_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClientResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_code", models.CharField(max_length=80)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("designation", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["client__name", "full_name"],
                "unique_together": {("client", "employee_code")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyWorkEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("expected_working_days", models.IntegerField(default=0)),
                (
                    "days_worked",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "leave_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "extra_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_entries",
                        to="clients.client",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_entries",
                        to="timesheets.clientresource",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "client__name", "resource__full_name"],
                "unique_together": {("resource", "year", "month")},
            },
        ),
    ]
