# Generated by Django 6.0.4 on 2026-05-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_config", "0002_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workingdayconfig",
            name="month",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="workingdayconfig",
            name="working_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workingdayconfig",
            name="year",
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name="workingdayconfig",
            name="fri",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="workingdayconfig",
            name="mon",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="workingdayconfig",
            name="thu",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="workingdayconfig",
            name="tue",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="workingdayconfig",
            name="wed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="workingdayconfig",
            name="weekend_policy",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                default="unpaid",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workingdayconfig",
            unique_together={("client", "year", "month")},
        ),
    ]
