# Generated by Django 6.0.4 on 2026-05-29 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_config", "0007_alter_workingdayconfig_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(365)]
            ),
        ),
        migrations.AlterField(
            model_name="workingdayconfig",
            name="month",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workingdayconfig",
            name="working_days",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(366),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workingdayconfig",
            name="year",
            field=models.IntegerField(
                default=2026,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
    ]
